webapp/views/__init__.py
#
# Copyright 2021-2026, Johann Saunier
# SPDX-License-Identifier: AGPL-3.0-or-later
#
from webapp.views.admin import admin_views
from webapp.views.gear import gear_views
from webapp.views.inventory import inventory_views
from webapp.views.loan import loan_views
from webapp.views.main import main_views
from webapp.views.member import member_views

all_views = (main_views, gear_views, inventory_views, loan_views, member_views, admin_views)

webapp/views/main.py
#
# Copyright 2021-2026, Johann Saunier
# SPDX-License-Identifier: AGPL-3.0-or-later
#
import logging
from datetime import datetime

from flask import Blueprint, jsonify, redirect, request, url_for
from flask_babel import gettext as _
from flask_babel import lazy_gettext as _l
from flask_login import login_required
from weblib.roles import ROLE_USER, roles_required
from weblib.table import Table
from weblib.views import Tab, site

from webapp.forms import ServicingForm
from webapp.requests import (
	create_servicing, get_every_loans, get_items_in_servicing, get_items_to_service, get_loans, get_members_fullnames,
	unservice
)

_LOGGER = logging.getLogger(__name__)


main_views = Blueprint('main_views', __name__, template_folder="templates", static_folder="static")


@main_views.before_request
@login_required
def before_request():
	pass


TABS = {
	'overview': Tab('overview', _l("Overview")),
	'gear': Tab('gear', _l("Gear")),
	'loan': Tab('loan', _l("Loans"), {
		'collection': Tab('collection', _l("Collect")),
		'reintegration': Tab('reintegration', _l("Reintegrate")),
	}),
	'inventory': Tab('inventory', _l("Inventories"), {
	}),
	'member': Tab('member', _l("Members")),
	'statistics': Tab('statistics', _l("Statistics")),
	'admin': Tab('admin', _l("Admin"), {
		'tools': Tab('tools', _l("Tools")),
		'qrcode': Tab('qrcode', _l("QRCodes")),
	}),
}


site.set_tabs(TABS)


@main_views.route('/')
def index():
	return redirect(url_for(".overview"))


@main_views.route('/overview')
def overview():
	return site.render_page(
		items_to_service=get_items_to_service(),
		in_servicing=get_items_in_servicing(),
	)


@main_views.route('/overview/loans.table')
def overview_loans_table():
	table = Table("loans")
	table.build_from_request(get_loans())
	return jsonify(table.dict)


@main_views.route('/statistics')
def statistics():
	return site.render_page()


@main_views.route('/statistics/loans.table')
def statistics_loans_table():
	table = Table("loans", title=_l("Every loans"))
	table.build_from_request(get_every_loans())
	return jsonify(table.dict)


@main_views.route('/servicing/add', methods=['GET', 'POST'])
@roles_required(ROLE_USER)
def servicing_add():
	form = ServicingForm()
	form.member.choices = get_members_fullnames()
	if request.method == 'POST':
		if form.validate():
			_LOGGER.info("Add a servicing for item '%s' to the database", form.item_id.data)
			create_servicing(
				item=form.item_id.data,
				member=form.member.data,
				date=form.date.data,
				comment=form.comment.data,
			)
			unservice(form.item_id.data)
			return redirect(url_for('.overview'))
	else:
		form.item_id.data = request.args['id']
		form.date.data = datetime.now()
		return site.render_page(html_template="servicing_form.html",
			active_tab='overview',
			form=form,
		)

webapp/views/templates/admin.html
<ul class="nav nav-tabs">
	{% for tab in available_admin_tabs %}
	<li class="nav-item">
		{% if active_admin_tab.name == tab.name %}
		<a class="nav-link active" href="/admin/{{ tab.name }}">{{ tab.i18n }}</a>
		{% else %}
		<a class="nav-link" href="/admin/{{ tab.name }}">{{ tab.i18n }}</a>
		{% endif %}
	</li>
	{% endfor %}
</ul>

webapp/views/templates/gear/add.html
{% include "/gear/header.html" %}
{% import "/macros.html" as macros %}

{{ macros.new_form(form, _("Create"), "/gear/%s/%s/add_item" % (active_sub_tab.name, active_item.type)) }}

webapp/views/templates/gear/header.html
<ul class="nav nav-tabs mt-n3">
<!--
	mt-n3 is for negative margin but it is not enabled by default :( see here : https://getbootstrap.com/docs/5.2/utilities/spacing/#negative-margin
-->
	{% for item in available_items %}
	<li class="nav-item">
		<a id={{ "tab-l3-%s" % (item.type, ) }} class="nav-link {% if item.type == active_item.type %}active{% endif %}" href="/gear/{{ active_sub_tab.name }}/{{ item.type }}">{{ item.tab_name }}</a>
	</li>
	{% endfor %}
</ul>

webapp/views/templates/gear/item/add_servicing.html
{% include "/gear/header.html" %}
{% import "/macros.html" as macros %}

<h1>{{ gettext("Servicing of %(item)s", item=item) }}</h1>

{{ macros.new_form(form, _("Validate"), "/gear/item/add_servicing") }}

webapp/views/templates/gear/item/add_state.html
{% include "/gear/header.html" %}
{% import "/macros.html" as macros %}

<h1>{{ gettext("State of %(item)s", item=item) }}</h1>

{{ macros.new_form(form, _("Validate"), "/gear/item/add_state") }}

webapp/views/templates/gear/item/info.html
{% include "/gear/header.html" %}
{% import "/macros.html" as macros %}

<h1>{{ item_name }} {{ reference }}</h1>

{% if crud_step == "read" %}
	{% for table_name, table_params in tables.items() %}
		<h2>{{table_params.title}}</h2>
		{{ macros.dyn_table(table_name, url, has_create_button=False, has_searchbox=False) }}
	{% endfor %}
{% elif crud_step != "delete" %}
	{{ macros.new_form(form, _("Create") if crud_step == "create" else _("Update"), url ~ "/" ~ table_name ~ "/" ~ crud_step) }}
{% endif %}

webapp/views/templates/gear/item/modify.html
{% include "/gear/header.html" %}
{% import "/macros.html" as macros %}

<h1>{{ _("Item caracteristics") }}</h1>
{{ macros.new_form(form, _("Modify"), "/gear/item/modify") }}

webapp/views/templates/gear/item/modify_state.html
{% include "/gear/header.html" %}
{% import "/macros.html" as macros %}


<h2>{{ _("Gear") }}</h2>
{{ macros.new_form(form, _("Modify"), "/gear/item/modify_state") }}

webapp/views/templates/gear/item/move.html
{% include "/gear/header.html" %}
{% import "/macros.html" as macros %}

{{ macros.new_form(form, _("Move"), "/gear/move", on_cancel="/gear") }}

webapp/views/templates/gear/table.html
{% include "/gear/header.html" %}
{% import "/macros.html" as macros %}

{% if not active_gear_item.is_composite %}

<div class="row g-0">
	{{ macros.dyn_table("gear", content_url, has_create_button=False) }}
	<a id="btn-add-item" class="btn btn-primary" href="/gear/{{ active_sub_tab.name }}/{{ active_item.type }}/add_item">+</a>
	<h2 class="mt-4">{{ _("Trashcan") }}</h2>
	{{ macros.dyn_table("trashed_gear", content_url, has_create_button=False, has_searchbox=False) }}
</div>

{% else %}

<div class="row">
	<div class="col-6">
		<div id="accordion">
			{% for row in table.rows %}
				<div class="card">
					<div id="{{ row[1] }}" class="card-header" style="background-color: light-grey;">
						<h5 class="mb-0">
							<button class="btn btn-link" data-bs-toggle="collapse" data-bs-target="#collapse-{{ row[0] }}">
								{{ "Ref. %s : %s %s (N° Série %s)" % (row.reference, row.brand, row.model, row.serial_nb) }}
							</button>
						</h5>
					</div>
					<div id="collapse-{{ row[0] }}" class="collapse" data-bs-parent="#accordion">
						<div class="card-body">
							{% for child in row.children %}
							<div>
								<a href="/gear/move?id={{ child[0] }}" style="background-color:
									{%- if child[1] == _("second_stage") -%}
									SkyBlue
									{%- elif child[1] == _("manometer") -%}
									DarkOrange
									{%- else -%}
									Yellow
									{%- endif -%}!important;">
									{{ " ".join(child[1:]) }}
								</a>
							</div>
							{% endfor %}
						</div>
					</div>
				</div>
			{% endfor %}
			</div>
			<h1>{{ _("Orphans") }}</h1>

			{% for row in table.orphans %}
			<div class="card">
				<div id="{{ row[0] }}" class="card-header" style="background-color: Tan;">
					<a href="/gear/move?id={{ row[0] }}">
						{{ " ".join(row[1:]) }}
					</a>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</div>

{% endif %}

webapp/views/templates/inventory.html
{% import "/macros.html" as macros %}
<div class="row">
	{% if is_in_progress %}
	<div class="col">
		<a id="btn-stop-campaign" class="btn btn-warning col-sm-3 mt-3" href="/inventory?stop=true">{{ gettext("Stop %(date)s's inventory campaign", date=running_inventory_date) }}</a>
	</div>
	<div class="form-group mt-5">
		{{ _("Start inventory of these items:") }}
		{{ macros.new_form(form, has_submit=False) }}
	</div>
	{{ macros.dyn_table("current_remaining_items", url_for("inventory_views.inventory_tab"), has_create_button=False, has_searchbox=False) }}
	{% else %}
		{{ macros.dyn_table("inventories", url_for("inventory_views.inventory_tab"), has_create_button=False, has_searchbox=False) }}
		{% if not has_been_started_today %}
			<div class="col">
				<a id="btn-start-campaign" class="btn btn-primary col-sm-3 mt-4" href="/inventory?start=true">{{ _("Start inventory campaign") }}</a>
			</div>
		{% endif %}
	{% endif %}
</div>

webapp/views/templates/inventory/info.html
{% import "/macros.html" as macros %}
<div id="inventory_info">
		<h1>{{ gettext("%(date)s's inventory", date=date) }}</h1>

		{% if prices_by_item_type %}
		<div class="mt-1">
			<table name="prices_by_item_type">
				<thead>
					<tr>
						<th>{{ _("Items estimations") }}</th>
					</tr>
				</thead>
				<tbody>
					{% for item, price in prices_by_item_type %}
					<tr>
						<td>{{ item }}</td>
						<td><b>{{ price }}€<b></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		{% endif %}

		{% if nb_of_items_by_type %}
		<div class="mt-1">
			<table name="nb_of_items_by_type">
				<thead>
					<tr>
						<th>{{ _("Number of present items") }}</th>
					</tr>
				</thead>
				<tbody>
					{% for item, nb in nb_of_items_by_type %}
					<tr>
						<td>{{ item }}</td>
						<td><b>{{ nb }}<b></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		{% endif %}

		{% if total_price %}
		<div class="mt-1">
			{{ _("Total inventory estimation") }} : <b>{{ total_price }}€</b>
		</div>
		{% endif %}

		{% if missing_items %}
		<div class="mt-3">
			<table name="missing_items">
				<thead>
					<tr>
						<th>{{ _("Missing items") }}</th>
					</tr>
				</thead>
				<tbody>
					{% for item in missing_items %}
					<tr>
						<td>{{ item }}</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		{% endif %}

		{% if unusable_items %}
		<div class="mt-3">
			<table name="unusable_items">
				<thead>
					<tr>
						<th>{{ _("Unusable items") }}</th>
					</tr>
				</thead>
				<tbody>
					{% for item in unusable_items %}
					<tr>
						<td>{{ item }}</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		{% endif %}

		{% if uninventoried_items %}
		<div class="mt-3">
			<table name="uninventoried_items">
				<thead>
					<tr>
						<th>{{ _("Uninventoried items") }}</th>
					</tr>
				</thead>
				<tbody>
					{% for item in uninventoried_items %}
					<tr>
						<td>{{ item }}</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		{% endif %}

</div>

webapp/views/templates/loan/collection.html
{% import "/macros.html" as macros %}

{{ macros.new_form(form, _("Collect"), url_for(".loan_collection_json"), has_submit=not use_scanner) }}
{% if use_scanner %}
<div id="barcode-reader-field" class="shown"></div>
	{% for ref in fake_qrcodes %}
	<button class="btn btn-danger fake-qrcode-btn mb-3">{{ ref }}</button>
	{% endfor %}
{% endif %}
<div id="borrow-popup" class="alert hidden" role="alert"></div>
<button type="button" id="degraded-mode-btn" class="btn btn-primary mt-5 {{ 'active' if not use_scanner else '' }}" data-bs-toggle="button" autocomplete="off">{{ _('Switch to manual mode') if use_scanner else _('Switch to scan mode') }}</button>

webapp/views/templates/loan/reintegration.html
{% import "/macros.html" as macros %}

{% if form %}
{{ macros.new_form(form, _("Give back"), "/loan/reintegration") }}
{% else %}
<h1>{{ _("Nothing to give back") }}</h1>
{% endif %}

webapp/views/templates/overview.html
{% import "/macros.html" as macros %}
<div id="overview">

		<h1>{{ _("Loans") }}</h1>
		{{ macros.dyn_table("loans", url_for("main_views.overview"), has_create_button=False) }}

		{% if items_to_service %}
		<h1>{{ _("Need of servicing") }}</h1>
		<table name="need_servicing">
			<thead>
				<tr>
					<th>{{ _("Item") }}</th>
					<th>{{ _("Remaining usages") }}</th>
				</tr>
			</thead>
			<tbody>
				{% for row in items_to_service %}
				<tr>
					<td><a href="/gear/service?id={{ row[0] }}">{{ row[1] }}</a></td>
					<td>{{ row[2] }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% endif %}

		{% if in_servicing %}
		<h1>{{ _("In servicing") }}</h1>
		<table name="in_servicing">
			<thead>
				<tr>
					<th>{{ _("Item") }}</th>
				</tr>
			</thead>
			<tbody>
				{% for row in in_servicing %}
				<tr>
					<td><a href="/servicing/add?id={{ row[0] }}">{{ row[1] }}</a></td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% endif %}

</div>

webapp/views/templates/servicing_form.html
{% import "/macros.html" as macros %}

{{ macros.new_form(form, _("Add"), "/servicing/add", on_cancel="/overview") }}

webapp/views/templates/statistics.html
{% import "/macros.html" as macros %}
<div id="overview">

		<h1>{{ _("Every loans") }}</h1>
		{{ macros.dyn_table("loans", url_for("main_views.statistics"), has_create_button=False) }}

</div>